### ISSUE TITLE
关于上传限速的思路

### ISSUE THREAD

**Issue by aifeiasdf** [luvjoey1996/resty-upload-rate-limit#1]
你好luvjoey1996  我看了下这种限速思路，这种做法是将client的上报数据滞留在套接字层面，延缓应用层的读取是吗？ 如果是的话我想请教下，这种思路会导致缓冲区被撑爆吗？

**Comment by luvjoey1996** [comment]
会的

**Comment by mike96265** [comment]
> 你好luvjoey1996 我看了下这种限速思路，这种做法是将client的上报数据滞留在套接字层面，延缓应用层的读取是吗？ 如果是的话我想请教下，这种思路会导致缓冲区被撑爆吗？

就是放在缓冲区不读取，tcp 的 流量控制自己会起作用的.
